/** Text labels and client-side UI limits for the Mini App. */

/** User-facing Mini App copy shared across features. */
export const TEXTS = Object.freeze({
    loading: "Loading",
    ready: "Ready",
    browserPreview: "Browser preview",
    authError: "Open this Mini App inside Telegram.",
    configLoadFailed: "Could not load Mini App config.",
    pricesLoadFailed: "Could not load market prices.",
    alertsLoadFailed: "Could not load alerts.",
    alertHistoryLoadFailed: "Could not load alert history.",
    alertCreateFailed: "Could not create alert.",
    alertDisableFailed: "Could not disable alert.",
    riskCheckFailed: "Could not check this token.",
    whaleSettingsLoadFailed: "Could not load whale alert settings.",
    whaleSettingsSaveFailed: "Could not save whale alert settings.",
    whaleEventsLoadFailed: "Could not load whale events.",
    alertCreated: "Alert created.",
    alertDisabled: "Alert disabled.",
    tokenChecked: "Token checked.",
    whaleSettingsSaved: "Whale alert settings saved.",
    saving: "Saving",
    emptyWhaleEvents: "No whale events have been detected yet.",
    whaleAlertsEnabledStatus: "Whale alerts are enabled.",
    whaleAlertsDisabledStatus: "Whale alerts are disabled.",
    whaleTrackedAssetsLabel: "Tracked assets",
    whaleTrackedAssetsFallback: "Supported coins from app config",
    whaleEventTypesLabel: "Event types",
    whaleSimulatedProviderWarning:
        "This MVP uses a simulated whale provider. Events are demo market movements, not live on-chain tracking.",
    saveWhaleSettingsButton: "Save settings",
    whaleMinUsdRequired: "Please enter a minimum USD value.",
    whaleMinUsdInvalid: "Please enter a valid minimum USD value.",
    whaleMinUsdTooLowTemplate: "Minimum whale alert value is {minValue} USD.",
    whaleMinUsdTooHighTemplate: "Maximum whale alert value is {maxValue} USD.",
    loadMoreWhaleEventsButton: "Load more",
    loadingMoreWhaleEventsButton: "Loading...",
    networkLabel: "Network",
    amountLabel: "Amount",
    valueLabel: "Value",
    detectedAtLabel: "Detected",
    transactionLabel: "Transaction",
    emptyPrices: "No prices are available right now.",
    emptyActiveAlerts: "You do not have active alerts yet.",
    emptyAlertHistory: "Your alert history is empty.",
    telegramOnlyFeature: "This action is available only inside Telegram.",
    refreshPricesButton: "Refresh",
    refreshPricesCooldownTemplate: "Refresh in {seconds}s",
    refreshPricesCooldownToastTemplate: "Prices can be refreshed again in {seconds}s.",
    chooseCoinPlaceholder: "Choose coin",
    chooseConditionPlaceholder: "Choose condition",
    chooseChainPlaceholder: "Choose blockchain",
    noCoinsAvailable: "No coins available.",
    noConditionsAvailable: "No conditions available.",
    noChainsAvailable: "No blockchains available.",
    coinRequired: "Please choose a coin.",
    conditionRequired: "Please choose a condition.",
    chainRequired: "Please choose a blockchain.",
    contractAddressRequired: "Please enter a contract address.",
    targetPriceRequired: "Please enter a target price greater than zero.",
    targetPriceInvalid: "Please enter a valid target price.",
    targetPriceTooHighTemplate: "Maximum allowed target price is {maxPrice}.",
    increaseTargetPriceLabel: "Increase target price",
    decreaseTargetPriceLabel: "Decrease target price",
    activeAlertsTitle: "My active alerts",
    activeAlertsDescription: "Active alerts are still monitored by the worker.",
    alertHistoryTitle: "Alert history",
    alertHistoryDescription:
        "Triggered and disabled alerts stay here for history.",
    createdAtLabel: "Created",
    triggeredAtLabel: "Triggered",
    disableButton: "Disable",
    loadMoreHistoryButton: "Load more",
    loadingMoreHistoryButton: "Loading...",
    disableConfirmTitle: "Disable alert?",
    disableConfirmDescriptionTemplate:
        "You are about to disable {symbol} {condition} ${price}. It will stay in history.",
    cancelDisableButton: "Cancel",
    confirmDisableButton: "Disable",
    riskResultTitle: "Token risk report",
    riskLevelLabel: "Risk level",
    riskSignalsLabel: "Detected signals",
    detectedSignalsLabel: "Detected signals",
    chainLabel: "Chain",
    contractLabel: "Contract",
    noRiskSignals: "No normalized risk signals were detected.",
    riskCheckSubmitButton: "Check token",
    riskSignalDetectedValue: "detected",
    riskDisclaimer:
        "This report is based on automated checks and does not guarantee that the token is safe.",
    riskStatusLabels: Object.freeze({
        low: "Low risk",
        medium: "Medium risk",
        high: "High risk",
        unknown: "Unknown risk",
    }),
    riskLevelLabels: Object.freeze({
        low: "Low risk",
        medium: "Medium risk",
        high: "High risk",
        unknown: "Unknown risk",
    }),
    riskSignalLabels: Object.freeze({
        is_honeypot: "Honeypot behavior",
        cannot_sell_all: "Cannot sell all tokens",
        is_blacklisted: "Blacklist function",
        is_proxy: "Proxy contract",
        hidden_owner: "Hidden owner",
        slippage_modifiable: "Sell tax can be changed",
        personal_slippage_modifiable: "Personal tax can be changed",
        selfdestruct: "Self-destruct function",
        owner_change_balance: "Owner can change balances",
        can_take_back_ownership: "Owner can take back ownership",
        is_mintable: "Mintable supply",
        external_call: "External contract calls",
        trading_cooldown: "Trading cooldown",
        buy_tax: "Buy tax",
        sell_tax: "Sell tax",
    }),
    whaleEventTypeLabels: Object.freeze({
        transfer: "Large transfer",
        exchange_inflow: "Exchange inflow",
        exchange_outflow: "Exchange outflow",
        unknown: "Unknown movement",
    }),
    conditionLabels: Object.freeze({
        above: "Above target price",
        below: "Below target price",
    }),
    compactConditionLabels: Object.freeze({
        above: "above",
        below: "below",
    }),
    alertStatusLabels: Object.freeze({
        active: "Active",
        triggered: "Triggered",
        disabled: "Disabled",
    }),
});

/** Client-side UI limits that mirror backend validation rules. */
export const UI_LIMITS = Object.freeze({
    pricesRefreshCooldownSeconds: 15,
    alertHistoryPageSize: 20,
    whaleEventsPageSize: 20,
    minWhaleUsd: 1000,
    maxWhaleUsd: 100000000000,
    maxTargetPriceUsd: 1000000000,
});
