"""add whale alerts

Revision ID: 25b904257766
Revises: 0060d6798583
Create Date: 2026-05-20 14:09:32.044634

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "25b904257766"
down_revision: str | None = "0060d6798583"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply database changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "whale_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("coin_id", sa.String(length=100), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("network", sa.String(length=50), nullable=False),
        sa.Column("transaction_hash", sa.String(length=255), nullable=False),
        sa.Column("from_address", sa.String(length=255), nullable=True),
        sa.Column("to_address", sa.String(length=255), nullable=True),
        sa.Column("amount", sa.Numeric(precision=36, scale=18), nullable=False),
        sa.Column("amount_usd", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "transfer",
                "exchange_inflow",
                "exchange_outflow",
                "unknown",
                name="whale_event_type",
            ),
            nullable=False,
        ),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_whale_events")),
        sa.UniqueConstraint(
            "transaction_hash", name=op.f("uq_whale_events_transaction_hash")
        ),
    )
    op.create_index(
        "ix_whale_events_amount_usd", "whale_events", ["amount_usd"], unique=False
    )
    op.create_index(
        "ix_whale_events_coin_detected_at",
        "whale_events",
        ["coin_id", "detected_at"],
        unique=False,
    )
    op.create_table(
        "whale_alert_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("min_usd_value", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_whale_alert_settings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_whale_alert_settings")),
    )
    op.create_index(
        op.f("ix_whale_alert_settings_user_id"),
        "whale_alert_settings",
        ["user_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Rollback database changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_whale_alert_settings_user_id"), table_name="whale_alert_settings"
    )
    op.drop_table("whale_alert_settings")
    op.drop_index("ix_whale_events_coin_detected_at", table_name="whale_events")
    op.drop_index("ix_whale_events_amount_usd", table_name="whale_events")
    op.drop_table("whale_events")
    op.execute("DROP TYPE IF EXISTS whale_event_type")
    # ### end Alembic commands ###
