"""initial

Revision ID: bc4cc12712c9
Revises:
Create Date: 2026-05-11 09:59:31.884091

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bc4cc12712c9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply database changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True)
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("coin_id", sa.String(length=100), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("target_price", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column(
            "condition",
            sa.Enum("above", "below", name="alert_condition"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("active", "triggered", "disabled", name="alert_status"),
            nullable=False,
        ),
        sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_alerts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    op.create_index(
        "ix_alerts_status_coin_condition",
        "alerts",
        ["status", "coin_id", "condition"],
        unique=False,
    )
    op.create_index(op.f("ix_alerts_user_id"), "alerts", ["user_id"], unique=False)
    op.create_table(
        "token_checks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("chain", sa.String(length=50), nullable=False),
        sa.Column("contract_address", sa.String(length=255), nullable=False),
        sa.Column(
            "risk_level",
            sa.Enum("low", "medium", "high", "unknown", name="risk_level"),
            nullable=False,
        ),
        sa.Column("flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "raw_response", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_token_checks_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_token_checks")),
    )
    op.create_index(
        "ix_token_checks_chain_contract",
        "token_checks",
        ["chain", "contract_address"],
        unique=False,
    )
    op.create_index(
        op.f("ix_token_checks_user_id"), "token_checks", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Rollback database changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_token_checks_user_id"), table_name="token_checks")
    op.drop_index("ix_token_checks_chain_contract", table_name="token_checks")
    op.drop_table("token_checks")
    op.drop_index(op.f("ix_alerts_user_id"), table_name="alerts")
    op.drop_index("ix_alerts_status_coin_condition", table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
