"""Button labels and button-level UI markers for Telegram inline keyboards."""

MAIN_MENU_PRICES_BUTTON = "📈 Prices"
MAIN_MENU_ALERTS_BUTTON = "📋 Alerts"
MAIN_MENU_MINI_APP_BUTTON = "📱 Open Mini App"
MAIN_MENU_RISK_CHECK_BUTTON = "🛡 Token risk check"
MAIN_MENU_WHALES_BUTTON = "🐋 Whales"
MAIN_MENU_ABOUT_BUTTON = "ℹ️ About"

BACK_TO_MAIN_MENU_BUTTON = "⬅️ Main menu"
BACK_TO_ALERTS_BUTTON = "⬅️ Alerts"
BACK_BUTTON = "⬅️ Back"
CANCEL_BUTTON = "✖️ Cancel"

PRICES_REFRESH_BUTTON = "🔄 Refresh"

ALERTS_CREATE_BUTTON = "➕ Create alert"
ALERTS_LIST_BUTTON = "📋 My alerts"
ALERTS_HISTORY_BUTTON = "📋 My alerts"
ALERTS_DISABLE_BUTTON = "❌ Disable"
ALERTS_DELETE_BUTTON = ALERTS_DISABLE_BUTTON
ALERTS_ABOVE_BUTTON = "Above"
ALERTS_BELOW_BUTTON = "Below"

ALERTS_FILTER_SELECTED_EMOJI = "✅"
ALERTS_FILTER_ACTIVE_BUTTON = "Active"
ALERTS_FILTER_HISTORY_BUTTON = "History"
ALERTS_FILTER_ALL_BUTTON = ALERTS_FILTER_HISTORY_BUTTON

ALERTS_FILTER_TRIGGERED_BUTTON = "Triggered"

ALERTS_PREVIOUS_PAGE_BUTTON = "⬅️"
ALERTS_NEXT_PAGE_BUTTON = "➡️"
ALERTS_PAGE_BUTTON_TEMPLATE = "{page}/{total_pages}"

RISK_CHECK_START_BUTTON = "🔎 Check token"

WHALES_ENABLE_BUTTON = "✅ Enable alerts"
WHALES_DISABLE_BUTTON = "❌ Disable alerts"
WHALES_CHANGE_THRESHOLD_BUTTON = "💵 Change threshold"
WHALES_EVENTS_BUTTON = "📋 Recent events"
WHALES_PREVIOUS_PAGE_BUTTON = "⬅️"
WHALES_NEXT_PAGE_BUTTON = "➡️"
WHALES_PAGE_BUTTON_TEMPLATE = "{page}/{total_pages}"

NOTIFICATION_DISMISS_BUTTON = "🗑 Delete"
